export const TOKEN_EXPIRATION_TIME = 3600000;
export const TOKEN_REFRESH_EXPIRATION_TIME = 604800000;
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
export const TOKEN_REFRESH_EXPIRED = 'TOKEN_REFRESH_EXPIRED';
export const TOKEN_OK = 'TOKEN_OK';
